version: 1.2
workflows:
  - subclass: WDL
    name: kleborate
    primaryDescriptorPath: /kleborate.wdl
    testParameterFiles:
      - /kleborate.inputs.json
    description: "WDL for modular Kleborate analysis of *Klebsiella pneumoniae* genome assemblies"
    authors:
      - Gerald Mboowa <gmboowa@gmail.com>


